version: '3.9'

services:
  postgres_service:
    image: postgres:16
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app
    ports:
      - "5434:5434"
    networks:
      - app-net
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
#      - ./sql_app/scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "app_user"]
      interval: 5s
      retries: 5
    restart: always

#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: pgadmin_password
#    ports:
#      - "8070:8070"
#    networks:
#      - app-net
#    restart: always

#  app-webserver:
#    image: app_image:v1
#    ports:
#      - "80:80"
#    networks:
#      - app-net
#    restart: always
#    depends_on:
#      postgres_service:
#        condition: service_healthy

volumes:
  postgres-db-volume:

networks:
  app-net:
    driver: bridge
